version: "3.7"

services:
   db:
     image: "mongo:4.0.9"
     restart: always
     ports:
       - "27017:27017"
     volumes:
       - ./data/db:/usr/data/db
     environment:
       - MONGO_INITDB_ROOT_USERNAME=potato
       - MONGO_INITDB_ROOT_PASSWORD=potato123