version: "3"

services:
   db:
     image: "mongo:4.0.9"
     restart: always
     ports:
       - "27027:27027"
     volumes:
       - ./data/db:/usr/data/db
     environment:
       - MONGO_INITDB_ROOT_USERNAME=potato
       - MONGO_INITDB_ROOT_PASSWORD=potato123
  api:
    build:
      dockerfile: Dockerfile
      context: ./
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
