version: "3.7"

services:
   db:
     image: "mongo:4.0.9"
     restart: always
     ports:
       - "27027:27017"
     volumes:
       - ./data/db:/usr/data/db
     environment:
       - MONGO_HOST=localhost
       - MONGO_PORT=27027
       - MONGO_INITDB_ROOT_USERNAME=potato
       - MONGO_INITDB_ROOT_PASSWORD=potato123
       - MONGO_INITDB_DATABASE=test